spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/es-house?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  # JPA配置
  jpa:
    show-sql: true
    generate-ddl: false  #不使用jpa生成sql
    hibernate:
      ddl-auto: validate #启动时校验数据库表结构，而不做增删改操作
      naming:
        #实体类字段直接映射
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # 实体类字段使用驼峰命名映射
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging:
  level:
    org:
      hibernate:
        SQL: debug
