#测试环境使用 H2 数据库，实现测试数据解耦合
spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:test             #使用内存模式
    schema: classpath:db/schema.sql   #指定建表结构SQL文件
    data: classpath:db/data.sql       #指定插入数据的SQL文件
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update                #必须加此配置，默认为none不会自动执行上边的脚本
logging:
  level:
    org:
      hibernate:
        SQL: debug
